ALTER TABLE event_artists
ADD COLUMN is_headliner BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN performance_order INTEGER NOT NULL DEFAULT 0,
ADD COLUMN start_time TIMESTAMPTZ,
ADD COLUMN end_time TIMESTAMPTZ; 